CC = g++
FLAGS = -std=c++11 -Wextra -Wall -Werror -Wno-sign-compare -Wno-unused-result -pedantic -O2 
FILES = TSuffixTree.cpp main.cpp
PROG = lab5

da5:
	$(CC) $(FLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o lab5